#page title
page_title                                : "Miss Out: block apps & websites"         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6541760507                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Miss Out                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Block apps & websites

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mathias Emil Mortensen
your_link                                 : https://mathiasemil.com                     
your_city                                 : Copenhagen                                
email_address                             : support@missout.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : https://mas.to/@mathiasemil



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Block Apps & Websites
    description                           : Built on Apple’s Screen Time API and Safari Content Blocker extension, Miss Out makes it easy to block specific apps and websites for better focus and peace of mind.
    fontawesome_icon_name                 : mobile
  
  - title                                 : Customizable Profiles
    description                           : Create tailored profiles to block apps and websites, making it simple to switch between setups for different needs, like avoiding spoilers or taking a break.
    fontawesome_icon_name                 : user-cog

  - title                                 : iCloud Sync
    description                           : Profiles and their settings sync across all your iOS and iPadOS devices. Enable a profile on one device to block apps and websites on all your devices.
    fontawesome_icon_name                 : cloud

  - title                                 : Instant Activation
    description                           : Activate or deactivate your profiles instantly using the app, widgets, control center, or Shortcuts, giving you full control with minimal effort.
    fontawesome_icon_name                 : bolt

  - title                                 : Stay Spoiler-Free
    description                           : Easily block content related to sports, TV shows, or movies so you can enjoy them on your own time, without spoilers.
    fontawesome_icon_name                 : eye-slash

  - title                                 : Take a Break from the News Cycle
    description                           : Use curated lists or custom profiles to block news websites and take a breather from constant headlines and updates.
    fontawesome_icon_name                 : newspaper

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
